Repository g6jamm/WishShare, pull requests merged in 2021-11, with the labels that each got.

#39 Add readme file
  README.md
Labels: enhancement

#40 Create production branch
  system.properties
Labels: new-feature

#38 Connect to database
  src/main/java/com/group6/wishshare/data/Util/.keep
  src/main/java/com/group6/wishshare/data/Util/DbManager.java
Labels: new-feature

#41 Create User class
  src/main/java/com/group6/wishshare/WishShareApplication.java
  src/main/java/com/group6/wishshare/domain/model/.keep
  src/main/java/com/group6/wishshare/domain/model/User.java
  src/main/java/com/group6/wishshare/domain/model/type/Gender.java
  src/test/java/com/group6/wishshare/domain/model/UserBuilderTest.java
Labels: new-feature

#46 Add schema to Db and add missing column
  README.md
  src/main/resources/data/install.sql
Labels: bug-fix

#45 wish model added
  src/main/java/com/group6/wishshare/data/repository/.keep
  src/main/java/com/group6/wishshare/data/repository/WishRepository.java
  src/main/java/com/group6/wishshare/domain/model/Wish.java
Labels: new-feature

#47 Wishlist andreas
  src/main/java/com/group6/wishshare/data/repository/WishListRepository.java
  src/main/java/com/group6/wishshare/domain/model/Wishlist.java
  src/main/java/com/group6/wishshare/domain/service/WishListService.java
Labels: new-feature

#51 changed method from void to boolean
  src/main/java/com/group6/wishshare/data/repository/WishRepository.java
Labels: enhancement

#54 Fix bad copypaste
  src/main/resources/templates/login.html
Labels: bug-fix

#59 Improve dbManager
  src/main/java/com/group6/wishshare/data/Util/DbManager.java
Labels: enhancement

#58 wish controller and some ui
  src/main/java/com/group6/wishshare/domain/service/WishService.java
  src/main/java/com/group6/wishshare/web/WishController.java
  src/main/resources/templates/createwish.html
  src/main/resources/templates/index.html
Labels: enhancement, new-feature

#56 Updated dashboard.html with wishlist
  src/main/java/com/group6/wishshare/data/repository/WishListRepository.java
  src/main/java/com/group6/wishshare/domain/service/WishListService.java
  src/main/java/com/group6/wishshare/web/FrontController.java
  src/main/java/com/group6/wishshare/web/WishlistController.java
  src/main/resources/templates/dashboard.html
Labels: enhancement, new-feature

#60 hide items on navbar
  src/main/resources/templates/fragments/navbar.html
Labels: enhancement

#61 Use date instead of string
  src/main/java/com/group6/wishshare/data/repository/DataFacade.java
  src/main/java/com/group6/wishshare/data/repository/UserRepository.java
  src/main/resources/data/install.sql
Labels: enhancement, bug-fix

#64 Edit wishlist
  src/main/java/com/group6/wishshare/data/repository/WishListRepository.java
  src/main/java/com/group6/wishshare/domain/service/WishListService.java
  src/main/java/com/group6/wishshare/web/WishlistController.java
Labels: enhancement

#65 Wish user
  src/main/java/com/group6/wishshare/data/repository/WishListRepository.java
  src/main/java/com/group6/wishshare/data/repository/WishRepository.java
  src/main/java/com/group6/wishshare/domain/service/WishListService.java
  src/main/java/com/group6/wishshare/domain/service/WishService.java
  src/main/java/com/group6/wishshare/web/WishController.java
  src/main/resources/templates/sharedwish.html
Labels: new-feature

#67 Should fix bug #57
  src/main/java/com/group6/wishshare/data/repository/DataFacade.java
  src/main/java/com/group6/wishshare/data/repository/UserRepository.java
  src/main/java/com/group6/wishshare/domain/service/LoginService.java
Labels: bug-fix

#68 Morewish
  src/main/java/com/group6/wishshare/data/repository/WishRepository.java
  src/main/java/com/group6/wishshare/domain/service/WishService.java
  src/main/java/com/group6/wishshare/web/WishController.java
  src/main/resources/templates/createwish.html
  src/main/resources/templates/editwish.html
  src/main/resources/templates/sharedwish.html
Labels: enhancement, new-feature

#69 Added functionality to delete wishlist
  src/main/java/com/group6/wishshare/data/repository/WishListRepository.java
  src/main/java/com/group6/wishshare/domain/service/WishListService.java
  src/main/java/com/group6/wishshare/web/WishlistController.java
  src/main/resources/static/css/custom-dashboard.css
  src/main/resources/templates/dashboard.html
Labels: new-feature

#70 Oop
  src/main/java/com/group6/wishshare/data/repository/DataFacade.java
  src/main/java/com/group6/wishshare/data/repository/UserRepository.java
  src/main/java/com/group6/wishshare/data/repository/WishListRepository.java
  src/main/java/com/group6/wishshare/domain/model/User.java
  src/main/java/com/group6/wishshare/domain/model/Wishlist.java
  src/main/java/com/group6/wishshare/domain/service/DataFacadeInterface.java
  src/main/java/com/group6/wishshare/domain/service/LoginService.java
  src/main/java/com/group6/wishshare/domain/service/UserService.java
  src/main/java/com/group6/wishshare/domain/service/WishListService.java
  src/main/java/com/group6/wishshare/web/FrontController.java
  src/main/java/com/group6/wishshare/web/WishController.java
  src/main/java/com/group6/wishshare/web/WishlistController.java
  src/main/resources/templates/fragments/navbar.html
Labels: enhancement, new-feature

#73 Start the work of shared wishlist
  src/main/java/com/group6/wishshare/data/repository/WishListRepository.java
  src/main/java/com/group6/wishshare/domain/model/Wishlist.java
  src/main/java/com/group6/wishshare/domain/service/WishListService.java
  src/main/java/com/group6/wishshare/web/WishController.java
  src/main/resources/data/install.sql
  src/main/resources/templates/shared-wishlist.html
  src/main/resources/templates/sharedwish.html
Labels: new-feature

#72 Oop2
  src/main/java/com/group6/wishshare/data/repository/UserRepository.java
  src/main/java/com/group6/wishshare/data/repository/WishListRepository.java
  src/main/java/com/group6/wishshare/domain/model/User.java
  src/main/java/com/group6/wishshare/domain/model/Wishlist.java
  src/main/java/com/group6/wishshare/domain/service/WishListService.java
  src/main/java/com/group6/wishshare/web/WishController.java
  src/main/java/com/group6/wishshare/web/WishlistController.java
Labels: enhancement

#74 Dbmanager update
  README.md
  src/main/java/com/group6/wishshare/data/Util/ConnectionType.java
  src/main/java/com/group6/wishshare/data/Util/DBSelector.java
  src/main/java/com/group6/wishshare/data/Util/DbManager.java
Labels: enhancement

#76 Userval
  src/main/java/com/group6/wishshare/data/repository/DataFacade.java
  src/main/java/com/group6/wishshare/data/repository/UserRepository.java
  src/main/java/com/group6/wishshare/domain/service/DataFacadeInterface.java
  src/main/java/com/group6/wishshare/domain/service/LoginService.java
  src/main/java/com/group6/wishshare/domain/service/UserService.java
  src/main/java/com/group6/wishshare/web/FrontController.java
  src/main/java/com/group6/wishshare/web/WishController.java
  src/main/java/com/group6/wishshare/web/WishlistController.java
  src/main/resources/templates/createwish.html
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: enhancement, bug-fix, new-feature

#77 Create token [WIP]
  src/main/java/com/group6/wishshare/data/repository/WishListRepository.java
  src/main/java/com/group6/wishshare/domain/service/WishListService.java
  src/main/java/com/group6/wishshare/web/WishController.java
  src/main/resources/data/install.sql
  src/main/resources/templates/dashboard.html
  src/main/resources/templates/error.html
  src/main/resources/templates/shared-wishlist.html
Labels: new-feature

#81 Bug fix
  src/main/java/com/group6/wishshare/data/repository/UserRepository.java
  src/main/java/com/group6/wishshare/data/repository/WishlistRepository.java
Labels: bug-fix

#88 Interfaces
  src/main/java/com/group6/wishshare/data/repository/DataFacade.java
  src/main/java/com/group6/wishshare/data/repository/UserRepository.java
  src/main/java/com/group6/wishshare/data/repository/UserRepositoryImpl.java
  src/main/java/com/group6/wishshare/data/repository/UserRepositoryStub.java
  src/main/java/com/group6/wishshare/data/repository/WishRepository.java
  src/main/java/com/group6/wishshare/data/repository/WishRepositoryImpl.java
  src/main/java/com/group6/wishshare/data/repository/WishRepositoryStub.java
  src/main/java/com/group6/wishshare/data/repository/WishlistRepository.java
  src/main/java/com/group6/wishshare/data/repository/WishlistRepositoryImpl.java
  src/main/java/com/group6/wishshare/data/repository/WishlistRepositoryStub.java
  src/main/java/com/group6/wishshare/data/repository/mysql/.keep
  src/main/java/com/group6/wishshare/domain/service/DataFacadeInterface.java
  src/main/java/com/group6/wishshare/domain/service/LoginService.java
  src/main/java/com/group6/wishshare/domain/service/UserService.java
  src/main/java/com/group6/wishshare/domain/service/WishlistService.java
  src/main/java/com/group6/wishshare/web/controller/LoginController.java
  src/main/java/com/group6/wishshare/web/controller/WishController.java
  src/main/java/com/group6/wishshare/web/controller/WishlistController.java
Labels: enhancement, new-feature

#89 Wish del
  src/main/java/com/group6/wishshare/data/repository/WishRepository.java
  src/main/java/com/group6/wishshare/data/repository/WishRepositoryImpl.java
  src/main/java/com/group6/wishshare/data/repository/WishRepositoryStub.java
  src/main/java/com/group6/wishshare/domain/service/WishService.java
  src/main/java/com/group6/wishshare/web/controller/WishController.java
  src/main/resources/templates/createwish.html
Labels: enhancement, new-feature

#91 Editwishlist
  src/main/java/com/group6/wishshare/data/repository/WishlistRepository.java
  src/main/java/com/group6/wishshare/data/repository/WishlistRepositoryImpl.java
  src/main/java/com/group6/wishshare/data/repository/WishlistRepositoryStub.java
  src/main/java/com/group6/wishshare/domain/model/BuilderInterface.java
  src/main/java/com/group6/wishshare/web/controller/WishController.java
  src/main/java/com/group6/wishshare/web/controller/WishlistController.java
  src/main/resources/templates/createwish.html
  src/main/resources/templates/dashboard.html
  src/main/resources/templates/editwish.html
  src/main/resources/templates/shared-wishlist.html
Labels: enhancement, bug-fix, new-feature

#96 Diagrams
  src/main/java/com/group6/wishshare/data/repository/UserRepository.java
  src/main/java/com/group6/wishshare/data/repository/WishRepository.java
  src/main/java/com/group6/wishshare/data/repository/mock/UserRepositoryStub.java
  src/main/java/com/group6/wishshare/data/repository/mock/WishRepositoryStub.java
  src/main/java/com/group6/wishshare/data/repository/mock/WishlistRepositoryStub.java
  src/main/java/com/group6/wishshare/data/repository/mysql/.keep
  src/main/java/com/group6/wishshare/data/repository/mysql/UserRepositoryImpl.java
  src/main/java/com/group6/wishshare/data/repository/mysql/WishRepositoryImpl.java
  src/main/java/com/group6/wishshare/data/repository/mysql/WishlistRepositoryImpl.java
  src/main/java/com/group6/wishshare/domain/exception/LoginException.java
  src/main/java/com/group6/wishshare/domain/model/Builder.java
  src/main/java/com/group6/wishshare/domain/model/User.java
  src/main/java/com/group6/wishshare/domain/model/Wish.java
  src/main/java/com/group6/wishshare/domain/model/Wishlist.java
  src/main/java/com/group6/wishshare/domain/service/LoginService.java
  src/main/java/com/group6/wishshare/domain/service/UserService.java
  src/main/java/com/group6/wishshare/domain/service/WishService.java
  src/main/java/com/group6/wishshare/domain/service/WishlistService.java
  src/main/java/com/group6/wishshare/web/controller/DashboardController.java
  src/main/java/com/group6/wishshare/web/controller/LoginController.java
  src/main/java/com/group6/wishshare/web/controller/WishController.java
  src/main/java/com/group6/wishshare/web/controller/WishlistController.java
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
Labels: enhancement

#97 Prod 2 :)
  .github/workflows/maven.yml
  src/main/java/com/group6/wishshare/data/repository/UserRepository.java
  src/main/java/com/group6/wishshare/data/repository/WishRepository.java
  src/main/java/com/group6/wishshare/data/repository/mock/UserRepositoryStub.java
  src/main/java/com/group6/wishshare/data/repository/mock/WishRepositoryStub.java
  src/main/java/com/group6/wishshare/data/repository/mock/WishlistRepositoryStub.java
  src/main/java/com/group6/wishshare/data/repository/mysql/.keep
  src/main/java/com/group6/wishshare/data/repository/mysql/UserRepositoryImpl.java
  src/main/java/com/group6/wishshare/data/repository/mysql/WishRepositoryImpl.java
  src/main/java/com/group6/wishshare/data/repository/mysql/WishlistRepositoryImpl.java
  src/main/java/com/group6/wishshare/data/util/DBManager.java
  src/main/java/com/group6/wishshare/domain/exception/LoginException.java
  src/main/java/com/group6/wishshare/domain/model/Builder.java
  src/main/java/com/group6/wishshare/domain/model/User.java
  src/main/java/com/group6/wishshare/domain/model/Wish.java
  src/main/java/com/group6/wishshare/domain/model/Wishlist.java
  src/main/java/com/group6/wishshare/domain/service/LoginService.java
  src/main/java/com/group6/wishshare/domain/service/UserService.java
  src/main/java/com/group6/wishshare/domain/service/WishService.java
  src/main/java/com/group6/wishshare/domain/service/WishlistService.java
  src/main/java/com/group6/wishshare/web/controller/DashboardController.java
  src/main/java/com/group6/wishshare/web/controller/LoginController.java
  src/main/java/com/group6/wishshare/web/controller/WishController.java
  src/main/java/com/group6/wishshare/web/controller/WishlistController.java
  src/main/resources/application.properties
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/test/java/com/group6/wishshare/WishShareApplicationTests.java
Labels: bug-fix
